# Generated by Django 5.0.7 on 2024-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_color_category_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
